import CryptoKit
import Foundation

public enum DarkbloomAccountPseudonym {
    private static let adjectives: [String] = ["swift","bold","calm","clever","bright","brave","cosmic","crystal","daring","deft","eager","earnest","electric","elegant","epic","fancy","fearless","fierce","fiery","fleet","fluffy","fond","frosty","fuzzy","gentle","giddy","glad","gleeful","glowing","golden","graceful","grand","great","happy","hardy","heroic","humble","iridescent","jolly","joyful","keen","kind","lively","lucid","lucky","lunar","magnetic","mellow","merry","mighty","misty","mythic","neat","noble","nimble","novel","opal","perky","plucky","polite","primal","prime","proud","pure","quick","quiet","radiant","rapid","rare","regal","robust","rosy","sage","savvy","shy","silent","silken","silver","snappy","snug","solar","sonic","spark","sparkly","splendid","spry","sublime","sunny","super","sweet","swirling","tame","tidy","trusty","twinkly","ultra","upbeat","valiant","velvet","vibrant","vigilant","vivid","warm","wavy","wild","winged","wise","witty","zappy","zealous","zesty","agile","airy","amber","ancient","aqua","arctic","atomic","auburn","autumn","azure","balmy","bashful","beamy","bonny","bouncy","breezy","bubbly","burning","buttery","candid","carmine","celestial","cerulean","cheerful","cheery","chestnut","chipper","chromatic","classic","cobalt","colossal","coral","cordial","cottony","courtly","creamy","crimson","crispy","cuddly","curious","dapper","dazzling","delightful","dewy","dignified","downy","dreamy","ducky","dynamic","earthy","ebony","ember","emerald","enchanted","energetic","evening","ever","festive","flame","florid","flowing","forest","fragrant","free","fresh","friendly","frosted","galactic","garnet","gentlemanly","ginger","glassy","glimmer","globular","glossy","good","graceful","granite","grassy","groovy","gusty","halcyon","hardworking","harmonic","hazel","hazy","healthy","hearty","helpful","hopeful","honest","iceberg","icy","imperial","indigo","ivory","jade","jaunty","jazzy","jovial","jubilant","lakeside","lavender","leafy","lemony","lighthearted","linen","loyal","luminous","lush","majestic","maple","marble","marvelous","matte","meadow","merry","merciful","meteoric","midnight","mild","mindful","minty","mirthful","modest","mossy","muddy","natural","nebula","neon","nightly","nutty","obsidian","ocean","olive","onyx","orchid","ornate","patient","peachy","pearl","peaceful","pebbly","pewter","pillowy","pine","playful","plenty","pluckier","plump","polished","ponderous","poppy"]
    private static let animals: [String] = ["otter","fox","owl","wolf","bear","lynx","deer","hawk","falcon","eagle","dolphin","whale","panda","tiger","lion","puma","jaguar","leopard","cheetah","horse","zebra","giraffe","moose","elk","badger","beaver","bunny","kit","kitten","puppy","raccoon","rabbit","squirrel","chipmunk","mouse","hedgehog","porcupine","mole","vole","ferret","weasel","stoat","marten","mink","shrew","armadillo","anteater","sloth","opossum","kangaroo","wombat","wallaby","koala","platypus","echidna","tapir","rhino","hippo","buffalo","bison","yak","camel","alpaca","llama","goat","sheep","lamb","calf","foal","pony","donkey","mule","piglet","boar","warthog","tapir","duck","goose","swan","heron","crane","stork","egret","ibis","flamingo","peacock","pheasant","quail","sparrow","finch","robin","wren","swallow","thrush","lark","bluebird","cardinal","canary","parrot","macaw","cockatoo","raven","crow","magpie","jay","puffin","penguin","albatross","tern","gull","pelican","kingfisher","woodpecker","hummingbird","kookaburra","kiwi","ostrich","emu","rhea","cassowary","toucan","hornbill","starling","mockingbird","nightingale","warbler","vireo","tanager","manatee","narwhal","orca","porpoise","seal","sealion","walrus","dugong","beluga","octopus","squid","cuttlefish","nautilus","starfish","urchin","anemone","crab","lobster","shrimp","krill","jellyfish","seahorse","stingray","manta","shark","marlin","swordfish","tuna","salmon","trout","pike","perch","carp","koi","cod","halibut","mackerel","snapper","grouper","barracuda","clownfish","angelfish","betta","guppy","tetra","minnow","anchovy","sardine","frog","toad","newt","salamander","axolotl","gecko","iguana","chameleon","komodo","monitor","skink","anole","tortoise","turtle","terrapin","crocodile","alligator","caiman","snake","python","viper","cobra","mamba","boa","butterfly","moth","dragonfly","ladybug","firefly","beetle","honeybee","bumblebee","ant","cricket","grasshopper","mantis","katydid","cicada","weevil","lacewing","caterpillar","snail","slug","earthworm","centipede","millipede","spider","scorpion","griffin","phoenix","dragon","unicorn","pegasus","kraken","sphinx","gryphon","hydra","basilisk","wyvern","drake","centaur","satyr","sprite","pixie","yeti","kelpie","selkie","kitsune","tanuki","qilin","wisp","firebird","thunderbird","rocbird","hippogriff","minotaur","manticore","chimera","harpy","siren"]

    public static func make(accountID: String) -> String {
        guard !accountID.isEmpty else { return "anon" }
        let digest = Array(SHA256.hash(data: Data(accountID.utf8)))
        let adjectiveIndex = (Int(digest[0]) << 8 | Int(digest[1])) % adjectives.count
        let animalIndex = (Int(digest[2]) << 8 | Int(digest[3])) % animals.count
        let number = (
            UInt32(digest[4]) << 24 |
            UInt32(digest[5]) << 16 |
            UInt32(digest[6]) << 8 |
            UInt32(digest[7])
        ) % 10_000
        return String(
            format: "%@-%@-%04u",
            adjectives[adjectiveIndex],
            animals[animalIndex],
            number
        )
    }
}
